// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package integration.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the Integration module
	public static integration.proxies.WeatherResponse cRS_GetWeatherBycity(IContext context, myfirstmodule.proxies.Employee _employee)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Employee", _employee == null ? null : _employee.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "Integration.CRS_GetWeatherBycity", params);
			return result == null ? null : integration.proxies.WeatherResponse.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}