// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Employee
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject employeeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Employee";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Designation("Designation"),
		City("City"),
		Date_Of_Joining("Date_Of_Joining"),
		Employee_Department("MyFirstModule.Employee_Department"),
		Employee_Account("MyFirstModule.Employee_Account");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Employee(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Employee"));
	}

	protected Employee(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject employeeMendixObject)
	{
		if (employeeMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Employee", employeeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Employee");

		this.employeeMendixObject = employeeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Employee.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Employee initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Employee.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Employee initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Employee(context, mendixObject);
	}

	public static myfirstmodule.proxies.Employee load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Employee.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Employee> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Employee> result = new java.util.ArrayList<myfirstmodule.proxies.Employee>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Employee" + xpathConstraint))
			result.add(myfirstmodule.proxies.Employee.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Designation
	 */
	public final java.lang.String getDesignation()
	{
		return getDesignation(getContext());
	}

	/**
	 * @param context
	 * @return value of Designation
	 */
	public final java.lang.String getDesignation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Designation.toString());
	}

	/**
	 * Set value of Designation
	 * @param designation
	 */
	public final void setDesignation(java.lang.String designation)
	{
		setDesignation(getContext(), designation);
	}

	/**
	 * Set value of Designation
	 * @param context
	 * @param designation
	 */
	public final void setDesignation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String designation)
	{
		getMendixObject().setValue(context, MemberNames.Designation.toString(), designation);
	}

	/**
	 * @return value of City
	 */
	public final java.lang.String getCity()
	{
		return getCity(getContext());
	}

	/**
	 * @param context
	 * @return value of City
	 */
	public final java.lang.String getCity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.City.toString());
	}

	/**
	 * Set value of City
	 * @param city
	 */
	public final void setCity(java.lang.String city)
	{
		setCity(getContext(), city);
	}

	/**
	 * Set value of City
	 * @param context
	 * @param city
	 */
	public final void setCity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String city)
	{
		getMendixObject().setValue(context, MemberNames.City.toString(), city);
	}

	/**
	 * @return value of Date_Of_Joining
	 */
	public final java.util.Date getDate_Of_Joining()
	{
		return getDate_Of_Joining(getContext());
	}

	/**
	 * @param context
	 * @return value of Date_Of_Joining
	 */
	public final java.util.Date getDate_Of_Joining(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Date_Of_Joining.toString());
	}

	/**
	 * Set value of Date_Of_Joining
	 * @param date_of_joining
	 */
	public final void setDate_Of_Joining(java.util.Date date_of_joining)
	{
		setDate_Of_Joining(getContext(), date_of_joining);
	}

	/**
	 * Set value of Date_Of_Joining
	 * @param context
	 * @param date_of_joining
	 */
	public final void setDate_Of_Joining(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date date_of_joining)
	{
		getMendixObject().setValue(context, MemberNames.Date_Of_Joining.toString(), date_of_joining);
	}

	/**
	 * @return value of Employee_Department
	 */
	public final myfirstmodule.proxies.Department getEmployee_Department() throws com.mendix.core.CoreException
	{
		return getEmployee_Department(getContext());
	}

	/**
	 * @param context
	 * @return value of Employee_Department
	 */
	public final myfirstmodule.proxies.Department getEmployee_Department(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Department result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Employee_Department.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Department.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Employee_Department
	 * @param employee_department
	 */
	public final void setEmployee_Department(myfirstmodule.proxies.Department employee_department)
	{
		setEmployee_Department(getContext(), employee_department);
	}

	/**
	 * Set value of Employee_Department
	 * @param context
	 * @param employee_department
	 */
	public final void setEmployee_Department(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Department employee_department)
	{
		if (employee_department == null)
			getMendixObject().setValue(context, MemberNames.Employee_Department.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Employee_Department.toString(), employee_department.getMendixObject().getId());
	}

	/**
	 * @return value of Employee_Account
	 */
	public final administration.proxies.Account getEmployee_Account() throws com.mendix.core.CoreException
	{
		return getEmployee_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of Employee_Account
	 */
	public final administration.proxies.Account getEmployee_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Employee_Account.toString());
		if (identifier != null)
			result = administration.proxies.Account.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Employee_Account
	 * @param employee_account
	 */
	public final void setEmployee_Account(administration.proxies.Account employee_account)
	{
		setEmployee_Account(getContext(), employee_account);
	}

	/**
	 * Set value of Employee_Account
	 * @param context
	 * @param employee_account
	 */
	public final void setEmployee_Account(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account employee_account)
	{
		if (employee_account == null)
			getMendixObject().setValue(context, MemberNames.Employee_Account.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Employee_Account.toString(), employee_account.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return employeeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Employee that = (myfirstmodule.proxies.Employee) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Employee";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
