// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package integration.proxies;

public class Main
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject mainMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Integration.Main";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Temp("Temp"),
		Main_WeatherResponse("Integration.Main_WeatherResponse");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Main(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Integration.Main"));
	}

	protected Main(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mainMendixObject)
	{
		if (mainMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Integration.Main", mainMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Integration.Main");

		this.mainMendixObject = mainMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Main.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static integration.proxies.Main initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return integration.proxies.Main.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static integration.proxies.Main initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new integration.proxies.Main(context, mendixObject);
	}

	public static integration.proxies.Main load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return integration.proxies.Main.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Temp
	 */
	public final java.math.BigDecimal getTemp()
	{
		return getTemp(getContext());
	}

	/**
	 * @param context
	 * @return value of Temp
	 */
	public final java.math.BigDecimal getTemp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Temp.toString());
	}

	/**
	 * Set value of Temp
	 * @param temp
	 */
	public final void setTemp(java.math.BigDecimal temp)
	{
		setTemp(getContext(), temp);
	}

	/**
	 * Set value of Temp
	 * @param context
	 * @param temp
	 */
	public final void setTemp(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal temp)
	{
		getMendixObject().setValue(context, MemberNames.Temp.toString(), temp);
	}

	/**
	 * @return value of Main_WeatherResponse
	 */
	public final integration.proxies.WeatherResponse getMain_WeatherResponse() throws com.mendix.core.CoreException
	{
		return getMain_WeatherResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of Main_WeatherResponse
	 */
	public final integration.proxies.WeatherResponse getMain_WeatherResponse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		integration.proxies.WeatherResponse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Main_WeatherResponse.toString());
		if (identifier != null)
			result = integration.proxies.WeatherResponse.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Main_WeatherResponse
	 * @param main_weatherresponse
	 */
	public final void setMain_WeatherResponse(integration.proxies.WeatherResponse main_weatherresponse)
	{
		setMain_WeatherResponse(getContext(), main_weatherresponse);
	}

	/**
	 * Set value of Main_WeatherResponse
	 * @param context
	 * @param main_weatherresponse
	 */
	public final void setMain_WeatherResponse(com.mendix.systemwideinterfaces.core.IContext context, integration.proxies.WeatherResponse main_weatherresponse)
	{
		if (main_weatherresponse == null)
			getMendixObject().setValue(context, MemberNames.Main_WeatherResponse.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Main_WeatherResponse.toString(), main_weatherresponse.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return mainMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final integration.proxies.Main that = (integration.proxies.Main) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Integration.Main";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
