// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package integration.proxies;

public class Weather
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject weatherMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Integration.Weather";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Weather_WeatherResponse("Integration.Weather_WeatherResponse");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Weather(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Integration.Weather"));
	}

	protected Weather(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject weatherMendixObject)
	{
		if (weatherMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Integration.Weather", weatherMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Integration.Weather");

		this.weatherMendixObject = weatherMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Weather.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static integration.proxies.Weather initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return integration.proxies.Weather.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static integration.proxies.Weather initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new integration.proxies.Weather(context, mendixObject);
	}

	public static integration.proxies.Weather load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return integration.proxies.Weather.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Weather_WeatherResponse
	 */
	public final integration.proxies.WeatherResponse getWeather_WeatherResponse() throws com.mendix.core.CoreException
	{
		return getWeather_WeatherResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of Weather_WeatherResponse
	 */
	public final integration.proxies.WeatherResponse getWeather_WeatherResponse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		integration.proxies.WeatherResponse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Weather_WeatherResponse.toString());
		if (identifier != null)
			result = integration.proxies.WeatherResponse.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Weather_WeatherResponse
	 * @param weather_weatherresponse
	 */
	public final void setWeather_WeatherResponse(integration.proxies.WeatherResponse weather_weatherresponse)
	{
		setWeather_WeatherResponse(getContext(), weather_weatherresponse);
	}

	/**
	 * Set value of Weather_WeatherResponse
	 * @param context
	 * @param weather_weatherresponse
	 */
	public final void setWeather_WeatherResponse(com.mendix.systemwideinterfaces.core.IContext context, integration.proxies.WeatherResponse weather_weatherresponse)
	{
		if (weather_weatherresponse == null)
			getMendixObject().setValue(context, MemberNames.Weather_WeatherResponse.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Weather_WeatherResponse.toString(), weather_weatherresponse.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return weatherMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final integration.proxies.Weather that = (integration.proxies.Weather) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Integration.Weather";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
