// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package integration.proxies;

public class WeatherResponse
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject weatherResponseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Integration.WeatherResponse";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Temp("Temp"),
		Main_WeatherResponse("Integration.Main_WeatherResponse"),
		Weather_WeatherResponse("Integration.Weather_WeatherResponse");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WeatherResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Integration.WeatherResponse"));
	}

	protected WeatherResponse(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject weatherResponseMendixObject)
	{
		if (weatherResponseMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Integration.WeatherResponse", weatherResponseMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Integration.WeatherResponse");

		this.weatherResponseMendixObject = weatherResponseMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'WeatherResponse.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static integration.proxies.WeatherResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return integration.proxies.WeatherResponse.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static integration.proxies.WeatherResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new integration.proxies.WeatherResponse(context, mendixObject);
	}

	public static integration.proxies.WeatherResponse load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return integration.proxies.WeatherResponse.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Temp
	 */
	public final java.math.BigDecimal getTemp()
	{
		return getTemp(getContext());
	}

	/**
	 * @param context
	 * @return value of Temp
	 */
	public final java.math.BigDecimal getTemp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Temp.toString());
	}

	/**
	 * Set value of Temp
	 * @param temp
	 */
	public final void setTemp(java.math.BigDecimal temp)
	{
		setTemp(getContext(), temp);
	}

	/**
	 * Set value of Temp
	 * @param context
	 * @param temp
	 */
	public final void setTemp(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal temp)
	{
		getMendixObject().setValue(context, MemberNames.Temp.toString(), temp);
	}

	/**
	 * @return value of Main_WeatherResponse
	 */
	public final integration.proxies.Main getMain_WeatherResponse() throws com.mendix.core.CoreException
	{
		return getMain_WeatherResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of Main_WeatherResponse
	 */
	public final integration.proxies.Main getMain_WeatherResponse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		integration.proxies.Main result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Main_WeatherResponse.toString());
		if (identifier != null)
			result = integration.proxies.Main.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Main_WeatherResponse
	 * @param main_weatherresponse
	 */
	public final void setMain_WeatherResponse(integration.proxies.Main main_weatherresponse)
	{
		setMain_WeatherResponse(getContext(), main_weatherresponse);
	}

	/**
	 * Set value of Main_WeatherResponse
	 * @param context
	 * @param main_weatherresponse
	 */
	public final void setMain_WeatherResponse(com.mendix.systemwideinterfaces.core.IContext context, integration.proxies.Main main_weatherresponse)
	{
		if (main_weatherresponse == null)
			getMendixObject().setValue(context, MemberNames.Main_WeatherResponse.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Main_WeatherResponse.toString(), main_weatherresponse.getMendixObject().getId());
	}

	/**
	 * @return value of Weather_WeatherResponse
	 */
	public final integration.proxies.Weather getWeather_WeatherResponse() throws com.mendix.core.CoreException
	{
		return getWeather_WeatherResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of Weather_WeatherResponse
	 */
	public final integration.proxies.Weather getWeather_WeatherResponse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		integration.proxies.Weather result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Weather_WeatherResponse.toString());
		if (identifier != null)
			result = integration.proxies.Weather.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Weather_WeatherResponse
	 * @param weather_weatherresponse
	 */
	public final void setWeather_WeatherResponse(integration.proxies.Weather weather_weatherresponse)
	{
		setWeather_WeatherResponse(getContext(), weather_weatherresponse);
	}

	/**
	 * Set value of Weather_WeatherResponse
	 * @param context
	 * @param weather_weatherresponse
	 */
	public final void setWeather_WeatherResponse(com.mendix.systemwideinterfaces.core.IContext context, integration.proxies.Weather weather_weatherresponse)
	{
		if (weather_weatherresponse == null)
			getMendixObject().setValue(context, MemberNames.Weather_WeatherResponse.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Weather_WeatherResponse.toString(), weather_weatherresponse.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return weatherResponseMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final integration.proxies.WeatherResponse that = (integration.proxies.WeatherResponse) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Integration.WeatherResponse";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
