// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package integration.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the Integration module

	public static java.lang.String getAPI_Key()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Integration.API_Key");
	}
}